import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import LenisScroll from "@/components/Lenis";

const funnelSans = localFont({
  src: "./fonts/FunnelSans-VF.ttf",
  variable: "--font-funnel-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Dylan | Sticky Effect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${funnelSans.className} antialiased max-w-full overflow-x-hidden`}
      >
        <LenisScroll/>
        {children}
      </body>
    </html>
  );
}
