import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const funnelSans = localFont({
  src: "./fonts/FunnelSans-VF.ttf",
  variable: "--font-funnel-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Dylan | Sticky Effect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${funnelSans.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
